wipwip

diff --git a/.github/workflows/dmr-test-ci.yml b/.github/workflows/dmr-test-ci.yml
--- a/.github/workflows/dmr-test-ci.yml
+++ b/.github/workflows/dmr-test-ci.yml
@@ -1,72 +1,91 @@
 name: DMR test CI config
 
 on:
-    push:
-        branches: ["dmr/oidc-in-ci"]
+  push:
+    branches: [ "dmr/oidc-in-ci" ]
 
 permissions:
   packages: read
 
 jobs:
-    end_to_end:
-        runs-on: ubuntu-latest
-#        services:
-#            postgres:
-#                image: postgres:13-alpine
-#                env:
-#                    POSTGRES_USER: postgres
-#                    POSTGRES_PASSWORD: postgres
-#                    POSTGRES_DB: syncv3
-#                ports:
-#                    - 5432:5432
-#                options: >-
-#                    --health-cmd pg_isready
-#                    --health-interval 10s
-#                    --health-timeout 5s
-#                    --health-retries 5
-        steps:
-#            - uses: actions/checkout@v3
-#
-#            - name: Install Go
-#              uses: actions/setup-go@v4
-#              with:
-#                go-version: 1.19
-#
-#            - name: Build
-#              run: go build ./cmd/syncv3
-#
-#            - name: Set up gotestfmt
-#              uses: GoTestTools/gotestfmt-action@v2
-#              with:
-#                token: ${{ secrets.GITHUB_TOKEN }}
+  end_to_end:
+    runs-on: ubuntu-latest
+    #        services:
+    #            postgres:
+    #                image: postgres:13-alpine
+    #                env:
+    #                    POSTGRES_USER: postgres
+    #                    POSTGRES_PASSWORD: postgres
+    #                    POSTGRES_DB: syncv3
+    #                ports:
+    #                    - 5432:5432
+    #                options: >-
+    #                    --health-cmd pg_isready
+    #                    --health-interval 10s
+    #                    --health-timeout 5s
+    #                    --health-retries 5
+    steps:
+      #            - uses: actions/checkout@v3
+      #
+      #            - name: Install Go
+      #              uses: actions/setup-go@v4
+      #              with:
+      #                go-version: 1.19
+      #
+      #            - name: Build
+      #              run: go build ./cmd/syncv3
+      #
+      #            - name: Set up gotestfmt
+      #              uses: GoTestTools/gotestfmt-action@v2
+      #              with:
+      #                token: ${{ secrets.GITHUB_TOKEN }}
 
-            - name: Declare Python dependencies
-              run: echo "matrix-synapse==1.90.0" > requirements.txt
+      - name: Declare Python dependencies
+        run: echo "matrix-synapse==1.90.0" > requirements.txt
 
-            - name: Install Python
-              uses: actions/setup-python@v4
-              with:
-                python-version: 3.11
-                cache: 'pip'
-                cache-dependency-path: 'requirements.txt'
+      - name: Install Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.11
+          cache: 'pip'
+          cache-dependency-path: 'requirements.txt'
 
-            - name: Install Synapse
+      - name: Install Synapse
+        run: |
+          pip install -r requirements.txt
+          pip list
+
+      - name: Configure Synapse
+        shell: bash
+        run: |
+          mkdir synapse
+          echo <<EOF
+          server_name: "exampledomain"
+          listeners:
+            - port: 8008
+              type: http
+              bind_addresses: ['::1', '127.0.0.1']
+              resources:
+                - names: [client]
+          database:
+            name: sqlite3
+            args:
+              database: synapse/homeserver.db
+          suppress_key_server_warning: true
+          report_stats: false
+          EOF > synapse/homeserver.config
+
+            - name: Run end-to-end tests
               run: |
-                pip install -r requirements.txt
-                pip list
-
-#            - name: Run end-to-end tests
-#              run: |
-#                set -euo pipefail
-#                ./run-tests.sh -count=1 -v -json . 2>&1 | tee test-e2e-runner.log | gotestfmt -hide all
-#              working-directory: tests-e2e
-#              shell: bash
-#              env:
-#                  SYNCV3_DB: user=postgres dbname=syncv3 sslmode=disable password=postgres host=localhost
-#                  SYNCV3_SERVER: http://localhost:8008
-#                  SYNCV3_SECRET: itsasecret
-#                  SYNCV3_MAX_DB_CONN: ${{ matrix.max_db_conns }}
-#                  E2E_TEST_SERVER_STDOUT: test-e2e-server.log
+                set -euo pipefail
+                ./run-tests.sh -count=1 -v -json . 2>&1 | tee test-e2e-runner.log | gotestfmt -hide all
+              working-directory: tests-e2e
+              shell: bash
+              env:
+                  SYNCV3_DB: user=postgres dbname=syncv3 sslmode=disable password=postgres host=localhost
+                  SYNCV3_SERVER: http://localhost:8008
+                  SYNCV3_SECRET: itsasecret
+                  E2E_TEST_SERVER_STDOUT: test-e2e-server.log
 #
 #            - name: Upload test log
 #              uses: actions/upload-artifact@v3
